CREATE TABLE season (
    seasonentryid INT AUTO_INCREMENT PRIMARY KEY,
    team_id INT,
    year INT,
    h_a CHAR(1),
    xG FLOAT,
    xGA FLOAT,
    npxG FLOAT,
    npxGA FLOAT,
    deep INT,
    deep_allowed INT,
    scored INT,
    missed INT,
    xpts FLOAT,
    result VARCHAR(255),
    date DATETIME,
    wins INT,
    draws INT,
    loses INT,
    pts INT,
    npxGD FLOAT,
    ppda_att INT,
    ppda_def INT,
    ppda_allowed_att INT,
    ppda_allowed_def INT
);

CREATE TABLE fut23 (
    Name VARCHAR(255) PRIMARY KEY,
    Team VARCHAR(255),
    FOREIGN KEY (Team) REFERENCES season(title)
    Country VARCHAR(255),
    League VARCHAR(255),
    Rating INT,
    Rare VARCHAR(255),
    Version_color VARCHAR(255),
    Position VARCHAR(10),
    Other_Positions VARCHAR(50),
    Version VARCHAR(50),
    Run_type VARCHAR(50),
    Price VARCHAR(50),
    Skill INT,
    Weak_foot INT,
    Attack_rate VARCHAR(10),
    Defense_rate VARCHAR(10),
    Pace INT,
    Shoot INT,
    Pass INT,
    Drible INT,
    Defense INT,
    Physical INT,
    Body_type VARCHAR(50),
    Height_cm VARCHAR(10),
    Weight_kg VARCHAR(10),
    Popularity INT,
    Base_Stats INT,
    In_Game_Stats INT,
    Game_version VARCHAR(50),
    Updated_at DATE
);
